### ISSUE TITLE
Audio Loading Problem in Javascript

### ISSUE THREAD

**Issue by devAdityaa** [devAdityaa/Man-vs-Frog#1]
When you try to load the game on your browser the background audio file (audio.mp3) fails to load. But if you rewrite the audio.play() function in the js file, the audio starts playing. This might be because of some error in the js file.
**What You Must Do:**
_You must correct this loading issue so that whenever i load my game in browser, the background audio plays_

**Comment by deepak-07** [comment]
Hi Dennis,
Have you hoisted this online somewhere so I can check the issue before jumping in the code?

**Comment by devAdityaa** [comment]
No, I havent hoisted. But you can solve the issue on your local system.

**Comment by AdityaChaudhary3** [comment]
hi devAdityaa,
I solved this issue, can you assign this to me?

**Comment by devAdityaa** [comment]
Yeah sure
