### ISSUE TITLE
Lag in Frog Animation

### ISSUE THREAD

**Issue by devAdityaa** [devAdityaa/Man-vs-Frog#3]
Whenever our hero jumps a frog, there's a skip in the animation of the frog's linear movement. This skip increases as our hero jump more frogs.

(you can play the game yourself, it is hoisted at https://devadityaa.github.io/Man-vs-Frog/ 
Arrows keys to move left, right & Jump)

**Your Task is Simple**
_Solve this CSS/JS animation issue so that there's no such lag in the fixed linear movement of the frog_

**Comment by tejashreeSurveJosh** [comment]
@devAdityaa https://github.com/devAdityaa/Man-vs-Frog/pull/6 check the pull request for the frog laging issue
